# Generated by Django 2.1.5 on 2019-10-18 15:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='内容')),
                ('source', models.CharField(blank=True, max_length=300, null=True, verbose_name='原文地址')),
                ('codeurl', models.TextField(blank=True, null=True, verbose_name='代码地址')),
                ('image', models.TextField(blank=True, null=True, verbose_name='图片地址')),
                ('keyword', models.CharField(blank=True, max_length=20, null=True, verbose_name='公众号关键词')),
                ('exist', models.BooleanField(default=True, verbose_name='是否存在')),
                ('readcount', models.IntegerField(default=0, verbose_name='阅读人数')),
                ('likecount', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('commentcount', models.IntegerField(default=0, verbose_name='评论人数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, unique=True, verbose_name='主机ip')),
                ('count', models.IntegerField(default=1, verbose_name='请求次数')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='请求开始时间')),
                ('last_active_time', models.DateTimeField(auto_now_add=True, verbose_name='最近请求时间')),
                ('is_lock', models.IntegerField(choices=[(0, '未锁定'), (1, '锁定')], default=0, verbose_name='ip状态')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('index', models.IntegerField(unique=True, verbose_name='序号')),
                ('content', models.TextField(verbose_name='内容')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('index', models.IntegerField(unique=True, verbose_name='序号')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
                ('readcount', models.IntegerField(default=0, verbose_name='阅读人数')),
                ('likecount', models.IntegerField(default=0, verbose_name='喜欢人数')),
                ('commentcount', models.IntegerField(default=0, verbose_name='评论人数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exist', models.BooleanField(default=True, verbose_name='是否存在')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
