# Generated by Django 2.1.5 on 2019-10-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='exist',
            field=models.BooleanField(default=True, verbose_name='是否存在'),
        ),
    ]
